# Generated by Django 5.1.1 on 2024-10-08 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactNo', models.CharField(blank=True, max_length=10, null=True)),
                ('About', models.CharField(blank=True, max_length=450, null=True)),
                ('Role', models.CharField(blank=True, max_length=150, null=True)),
                ('RegDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Content', models.TextField(blank=True, null=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateField(blank=True, null=True)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enotes.signup')),
            ],
        ),
    ]
